# Generated by Django 3.1.7 on 2021-04-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='form',
        ),
    ]
