# Generated by Django 3.1.7 on 2021-06-16 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='servicess',
        ),
    ]
