# Generated by Django 3.1.7 on 2021-06-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210616_0208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servicess',
            new_name='services',
        ),
    ]
