# Generated by Django 3.1.7 on 2021-06-16 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210616_0229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ser',
            new_name='serviceform',
        ),
    ]
