# Generated by Django 3.1.7 on 2021-06-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_needs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='needs',
            new_name='need1',
        ),
    ]
