# Generated by Django 3.1.7 on 2021-06-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210628_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('adderess', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='need1',
        ),
    ]
