# Generated by Django 3.1.7 on 2021-06-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210629_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='adderess',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donate',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donate',
            name='message',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donate',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donate',
            name='service',
            field=models.CharField(max_length=50),
        ),
    ]
